version: '2.1'

services:
  ignite:
    image: apacheignite/ignite:2.1.0
    environment:
      CONFIG_URI: https://raw.githubusercontent.com/ilysha-v/bln/master/src/main/resources/config.xml
  backend:
    image: default/bln
    expose: [ 8123 ]
    ports:
      - "127.0.0.1:8123:8123" # mac os docker limitations workaround
    depends_on: [ ignite ]